services:
  myserver:
    build:
      context: ./
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
  myMongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db
volumes:
  mongovolume:
